version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - world-db
    ports:
      - "8080:8080"

    #environment:
    #  - USER_INPUT=${YOUR_INPUT}

  # db is is db folder
  world-db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always